
export const CHANGE_MUSIC_TOOL = "CHANGE_MUSIC_TOOL"

export const ADD_NEW_BOX = "ADD_NEW_BOX"
export const REMOVE_BOX = "REMOVE_BOX"

export const ADD_COLUMN = "ADD_COLUMN"
export const REMOVE_COLUMN = "REMOVE_COLUMN"

export const GET_ACTIVE_MUSIC_TOOL = "GET_ACTIVE_MUSIC_TOOL"

export const UNDO_ELEMENT = "UNDO_ELEMENT"
export const REDO_ELEMENT = "REDO_ELEMENT"

export const TOGGLE_SOUND_PLAY = "TOGGLE_SOUND_PLAY"

export const ADD_ELE_TO_UNDO_STACK = "ADD_ELE_TO_UNDO_STACK"

export const UPDATE_ELEMENT = "UPDATE_ELEMENT"

export const CHANGE_IS_PLAYING = "CHANGE_IS_PLAYING"


export const ADD_SOUND = "ADD_SOUND"
export const CLEAR_ADDED_SOUNDS = "CLEAR_ADDED_SOUNDS"
export const SAVE_SOUND_COMBINATION = "SAVE_SOUND_COMBINATION"
export const TRIGGER_DOWNLOAD = "TRIGGER_DOWNLOAD"
export const CHANGE_BPM_FACTOR = "CHANGE_BPM_FACTOR"
export const CHANGE_ANIMATION = "CHANGE_ANIMATION"